parameters:
    gallery_directory: 'gallery/'
    image_size:
        image:
            width: 1024
            height: 768
        thumb:
            width: 150
            height: 150
framework:
    validation: {enable_annotations: true}

doctrine:
    orm:
        dql:
            string_functions:
                replace: GalleryBundle\DQL\Replace