services:
 gallery.image_service:
        class: GalleryBundle\Services\ImageService
        arguments: ["@doctrine.orm.entity_manager",'%gallery_directory%','%image_size%']
 gallery.dir_service:
        class: GalleryBundle\Services\DirService
        arguments: ["@doctrine.orm.entity_manager",'%gallery_directory%']
 gallery.templates_controller:
         class: GalleryBundle\Controller\TemplatesController
         arguments: ["@templating"]
 gallery.default_controller:
          class: GalleryBundle\Controller\DefaultController
          arguments: ["@templating","@service_container"]
 gallery.image_controller:
           class: GalleryBundle\Controller\ImageController
           arguments: ["@service_container"]
 gallery.dir_controller:
            class: GalleryBundle\Controller\DirectoryController
            arguments: ["@service_container"]