services:
 gallery.image_service:
        class: GalleryBundle\Services\ImageService
        arguments: ["@doctrine.orm.entity_manager"]
 gallery.dir_service:
        class: GalleryBundle\Services\DirService
        arguments: ["@doctrine.orm.entity_manager"]